---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.18.9}

inputs:
  - name: terraform-provider-alicloud
  - name: aliyun-cli

run:
  path: terraform-provider-alicloud/ci/tasks/pull-request.sh
params:
  ALICLOUD_ACCESS_KEY:   ""
  ALICLOUD_SECRET_KEY:   ""
  ALICLOUD_ACCOUNT_ID:   ""
  DING_TALK_TOKEN:       ""
  FC_SERVICE: ""
  FC_REGION: ""
  OSS_BUCKET_NAME:           ""
  OSS_BUCKET_REGION:         ""
  GITHUB_TOKEN: ""
  CONCOURSE_TARGET: ""
  CONCOURSE_TARGET_URL: ""
  CONCOURSE_TARGET_USER: ""
  CONCOURSE_TARGET_PASSWORD: ""
  CONCOURSE_TARGET_TRIGGER_PIPELINE_NAME: ""
  CONCOURSE_TARGET_TRIGGER_PIPELINE_JOB_NAME: ""
  CONCOURSE_FLY_VERSION: ""
  TRIGGER_TARGET_PIPELINE: ""