groups:
  - name: all
    jobs:
      - pull-request-integration-test-approve
      - pull-request-integration-test-comment
      - pull-request-docs-example
      - pull-request-docs-example-comment

shared:
  - &run
    task: terraformci
    file: terraform-provider-alicloud/ci/tasks/pull-request.yml
    params: &run-params
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_ACCOUNT_ID: {{alicloud_accound_id}}
      FC_SERVICE: {{alicloud_fc_service_name}}
      FC_REGION: {{alicloud_fc_region}}
      OSS_BUCKET_NAME: {{alicloud_oss_bucket_name}}
      OSS_BUCKET_REGION: {{alicloud_oss_bucket_region}}
      GITHUB_TOKEN: {{github_token}}

  - &run-example
    task: terraformci
    file: terraform-provider-alicloud/ci/tasks/docs-example.yml
    params:
      ALICLOUD_ACCESS_KEY: {{alicloud_access_key}}
      ALICLOUD_SECRET_KEY: {{alicloud_secret_key}}
      ALICLOUD_ACCOUNT_ID: {{alicloud_accound_id}}
      FC_SERVICE: {{alicloud_fc_service_name}}
      FC_REGION: {{alicloud_fc_region}}
      OSS_BUCKET_NAME: {{alicloud_oss_bucket_name}}
      OSS_BUCKET_REGION: {{alicloud_oss_bucket_region}}
      GITHUB_TOKEN: {{github_token_for_docs}}

jobs:
- name: pull-request-integration-test-approve
  plan:
  - in_parallel:
    - get: terraform-provider-alicloud
      resource: github-pr-approve
      trigger: true
      version: every
      params:
        source_path: .
    - get: aliyun-cli
      resource: aliyun-cli
  - <<: *run

- name: pull-request-integration-test-comment
  plan:
    - in_parallel:
        - get: terraform-provider-alicloud
          resource: github-pr-comment
          trigger: true
          version: every
          params:
            source_path: .
        - get: aliyun-cli
          resource: aliyun-cli
    - <<: *run

- name: pull-request-docs-example
  plan:
    - in_parallel:
        - get: terraform-provider-alicloud
          resource: github-pr-approve-docs
          trigger: true
          version: every
          params:
            source_path: .
        - get: aliyun-cli
          resource: aliyun-cli
    - <<: *run-example

- name: pull-request-docs-example-comment
  plan:
    - in_parallel:
        - get: terraform-provider-alicloud
          resource: github-pr-comment-docs
          trigger: true
          version: every
          params:
            source_path: .
        - get: aliyun-cli
          resource: aliyun-cli
        - get: terraform
          resource: terraform
        - get: github-cli
          resource: github-cli
    - <<: *run-example

resources:

- name: aliyun-cli
  type: s3
  source:
    access_key_id: {{aliyun_cli_access_key}}
    secret_access_key: {{aliyun_cli_secret_key}}
    bucket: {{aliyun_cli_bucket}}
    regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
    region_name: {{aliyun_cli_region}}
    endpoint: oss-((aliyun_cli_region)).aliyuncs.com

- name: github-pr-approve
  type: github-pr-comment-resource
  source:
    repository: aliyun/terraform-provider-alicloud
    access_token: {{github_token}}
    review_states: ["approved"]
    when: latest

- name: github-pr-comment
  type: github-pr-comment-resource
  source:
    repository: aliyun/terraform-provider-alicloud
    access_token: {{github_token}}
    review_states: ["commented"]
    when: latest
    comments: ["^approved$"]
    commenter_association: ["owner"]

- name: github-pr-approve-docs
  type: github-pr-comment-resource
  source:
    repository: aliyun/terraform-provider-alicloud
    access_token: {{github_token}}
    review_states: ["approved"]
    when: latest

- name: github-pr-comment-docs
  type: github-pr-comment-resource
  source:
    repository: aliyun/terraform-provider-alicloud
    access_token: {{github_token}}
    review_states: ["commented"]
    when: latest
    comments: ["^approved$"]

- name: terraform
  type: file-url
  source:
    url: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
    filename: terraform.zip

- name: github-cli
  type: file-url
  source:
    url: https://github.com/cli/cli/releases/download/v2.27.0/gh_2.27.0_linux_amd64.tar.gz
    filename: gh.tar.gz

resource_types:
  - name: github-pr-comment-resource
    type: docker-image
    source:
      repository: ndrjng/concourse-github-pr-comment-resource

  - name: file-url
    type: docker-image
    source:
      repository: pivotalservices/concourse-curl-resource
      tag: latest